CREATE TABLE IF NOT EXISTS candles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    instrument_key VARCHAR(64) NOT NULL,
    timeframe_unit VARCHAR(16) NOT NULL,
    timeframe_interval INTEGER NOT NULL,
    candle_ts TIMESTAMPTZ NOT NULL,
    open_price NUMERIC(18, 6) NOT NULL,
    high_price NUMERIC(18, 6) NOT NULL,
    low_price NUMERIC(18, 6) NOT NULL,
    close_price NUMERIC(18, 6) NOT NULL,
    volume BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_candle_price_range CHECK (low_price <= high_price),
    CONSTRAINT ck_candle_open_range CHECK (open_price >= low_price AND open_price <= high_price),
    CONSTRAINT ck_candle_close_range CHECK (close_price >= low_price AND close_price <= high_price),
    CONSTRAINT ck_candle_volume_non_negative CHECK (volume IS NULL OR volume >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_candle_tenant_symbol_tf_ts
ON candles (tenant_id, instrument_key, timeframe_unit, timeframe_interval, candle_ts);

CREATE INDEX IF NOT EXISTS idx_candle_lookup
ON candles (tenant_id, instrument_key, timeframe_unit, timeframe_interval, candle_ts);
