CREATE TABLE IF NOT EXISTS admin_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    username VARCHAR(128) NOT NULL,
    password_hash CHAR(64) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_admin_user_tenant_username UNIQUE (tenant_id, username)
);

CREATE INDEX IF NOT EXISTS idx_admin_user_tenant_active
    ON admin_user (tenant_id, username, active);

INSERT INTO admin_user (tenant_id, username, password_hash, active)
VALUES (
    'local-desktop',
    'admin',
    '7676aaafb027c825bd9abab78b234070e702752f625b752e55e55b48e607e358',
    TRUE
)
ON CONFLICT (tenant_id, username) DO NOTHING;
