CREATE TABLE IF NOT EXISTS upstox_migration_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    instrument_key VARCHAR(64) NOT NULL,
    timeframe_unit VARCHAR(16) NOT NULL,
    timeframe_interval INTEGER NOT NULL,
    next_from_date DATE NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    last_run_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    last_error TEXT,
    last_run_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_upstox_migration_state_stream UNIQUE (
        tenant_id,
        instrument_key,
        timeframe_unit,
        timeframe_interval
    )
);

CREATE INDEX IF NOT EXISTS idx_upstox_migration_state_pending
    ON upstox_migration_state (completed, tenant_id, instrument_key);
