CREATE TABLE IF NOT EXISTS admin_migration_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    instrument_key VARCHAR(128) NOT NULL,
    timeframe_unit VARCHAR(16) NOT NULL,
    timeframe_interval INTEGER NOT NULL,
    bootstrap_from_date DATE NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    progress_percent INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    next_from_date DATE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_admin_migration_job_stream UNIQUE (
        tenant_id,
        instrument_key,
        timeframe_unit,
        timeframe_interval
    )
);

CREATE INDEX IF NOT EXISTS idx_admin_migration_job_tenant_status
    ON admin_migration_job (tenant_id, status, updated_at DESC);
