CREATE TABLE IF NOT EXISTS option_chain_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    underlying_key VARCHAR(64) NOT NULL,
    expiry_date DATE NOT NULL,
    strike_price NUMERIC(18, 2) NOT NULL,
    snapshot_ts TIMESTAMPTZ NOT NULL,
    underlying_spot_price NUMERIC(18, 4),
    pcr NUMERIC(18, 6),

    call_instrument_key VARCHAR(64),
    call_ltp NUMERIC(18, 6),
    call_volume BIGINT,
    call_oi BIGINT,
    call_prev_oi BIGINT,
    call_bid_price NUMERIC(18, 6),
    call_bid_qty BIGINT,
    call_ask_price NUMERIC(18, 6),
    call_ask_qty BIGINT,
    call_iv NUMERIC(18, 6),
    call_delta NUMERIC(18, 6),
    call_gamma NUMERIC(18, 6),
    call_theta NUMERIC(18, 6),
    call_vega NUMERIC(18, 6),
    call_pop NUMERIC(18, 6),

    put_instrument_key VARCHAR(64),
    put_ltp NUMERIC(18, 6),
    put_volume BIGINT,
    put_oi BIGINT,
    put_prev_oi BIGINT,
    put_bid_price NUMERIC(18, 6),
    put_bid_qty BIGINT,
    put_ask_price NUMERIC(18, 6),
    put_ask_qty BIGINT,
    put_iv NUMERIC(18, 6),
    put_delta NUMERIC(18, 6),
    put_gamma NUMERIC(18, 6),
    put_theta NUMERIC(18, 6),
    put_vega NUMERIC(18, 6),
    put_pop NUMERIC(18, 6),

    row_payload JSONB NOT NULL,
    call_payload JSONB,
    put_payload JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_option_chain_strike_non_negative CHECK (strike_price >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_option_chain_snapshot_stream
ON option_chain_snapshots (tenant_id, underlying_key, expiry_date, strike_price, snapshot_ts);

CREATE INDEX IF NOT EXISTS idx_option_chain_latest_lookup
ON option_chain_snapshots (tenant_id, underlying_key, expiry_date, snapshot_ts DESC, strike_price);

CREATE INDEX IF NOT EXISTS idx_option_chain_history_lookup
ON option_chain_snapshots (tenant_id, underlying_key, snapshot_ts DESC);

CREATE TABLE IF NOT EXISTS option_chain_migration_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    underlying_key VARCHAR(64) NOT NULL,
    expiry_date DATE NOT NULL,
    bootstrap_completed BOOLEAN NOT NULL DEFAULT FALSE,
    last_snapshot_ts TIMESTAMPTZ,
    last_run_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    last_error TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_option_chain_migration_status
        CHECK (last_run_status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_option_chain_migration_state_stream
ON option_chain_migration_state (tenant_id, underlying_key, expiry_date);

CREATE INDEX IF NOT EXISTS idx_option_chain_migration_state_lookup
ON option_chain_migration_state (tenant_id, underlying_key, expiry_date);
