CREATE TABLE IF NOT EXISTS admin_trigger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    instrument_key VARCHAR(128) NOT NULL,
    timeframe_unit VARCHAR(16) NOT NULL,
    timeframe_interval INTEGER NOT NULL,
    event_source VARCHAR(32) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL,
    interval_value INTEGER,
    scheduled_at TIMESTAMPTZ,
    bootstrap_from_date DATE NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'STOPPED',
    last_run_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    last_error TEXT,
    last_run_at TIMESTAMPTZ,
    next_run_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_admin_trigger_tenant_status_next_run
    ON admin_trigger (tenant_id, status, next_run_at);

CREATE INDEX IF NOT EXISTS idx_admin_trigger_tenant_updated
    ON admin_trigger (tenant_id, updated_at DESC);
