CREATE TABLE IF NOT EXISTS admin_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_admin_session_token_hash UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_admin_session_tenant_expires
    ON admin_session (tenant_id, expires_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_session_expires
    ON admin_session (expires_at);

CREATE INDEX IF NOT EXISTS idx_upstox_migration_state_tenant_timeframe
    ON upstox_migration_state (tenant_id, timeframe_unit, timeframe_interval, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_option_chain_expiry_lookup
    ON option_chain_snapshots (tenant_id, underlying_key, expiry_date);

CREATE INDEX IF NOT EXISTS idx_admin_trigger_due_lookup
    ON admin_trigger (status, next_run_at);

CREATE INDEX IF NOT EXISTS idx_candles_history_cover
    ON candles (tenant_id, instrument_key, timeframe_unit, timeframe_interval, candle_ts DESC);
