ALTER TABLE admin_trigger
    ADD COLUMN IF NOT EXISTS job_key VARCHAR(64);

UPDATE admin_trigger
SET job_key = 'CANDLE_SYNC'
WHERE job_key IS NULL;

ALTER TABLE admin_trigger
    ALTER COLUMN job_key SET NOT NULL;

ALTER TABLE admin_trigger
    ALTER COLUMN job_key SET DEFAULT 'CANDLE_SYNC';

ALTER TABLE admin_trigger
    ALTER COLUMN timeframe_unit DROP NOT NULL;

ALTER TABLE admin_trigger
    ALTER COLUMN timeframe_interval DROP NOT NULL;

ALTER TABLE admin_trigger
    ALTER COLUMN bootstrap_from_date DROP NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_admin_trigger_job_key'
    ) THEN
        ALTER TABLE admin_trigger
            ADD CONSTRAINT ck_admin_trigger_job_key
                CHECK (job_key IN ('CANDLE_SYNC', 'TRADING_SIGNAL_REFRESH', 'TRADING_DAY_PARAM_REFRESH'));
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_admin_trigger_timeframe_requirements'
    ) THEN
        ALTER TABLE admin_trigger
            ADD CONSTRAINT ck_admin_trigger_timeframe_requirements
                CHECK (
                    (job_key IN ('CANDLE_SYNC', 'TRADING_SIGNAL_REFRESH')
                        AND timeframe_unit IS NOT NULL
                        AND timeframe_interval IS NOT NULL)
                    OR (job_key = 'TRADING_DAY_PARAM_REFRESH'
                        AND timeframe_unit IS NULL
                        AND timeframe_interval IS NULL)
                );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_admin_trigger_bootstrap_requirements'
    ) THEN
        ALTER TABLE admin_trigger
            ADD CONSTRAINT ck_admin_trigger_bootstrap_requirements
                CHECK (
                    (job_key = 'CANDLE_SYNC' AND bootstrap_from_date IS NOT NULL)
                    OR job_key IN ('TRADING_SIGNAL_REFRESH', 'TRADING_DAY_PARAM_REFRESH')
                );
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS trading_signal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    instrument_key VARCHAR(128) NOT NULL,
    timeframe_unit VARCHAR(16) NOT NULL,
    timeframe_interval INTEGER NOT NULL,
    signal_date DATE NOT NULL,
    previous_close NUMERIC(18, 6),
    current_close NUMERIC(18, 6),
    dma_9 NUMERIC(18, 6),
    dma_26 NUMERIC(18, 6),
    dma_110 NUMERIC(18, 6),
    signal VARCHAR(8) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_trading_signal_signal CHECK (signal IN ('BUY', 'SELL', 'HOLD'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_trading_signal_tenant_instrument_tf_day
    ON trading_signal (tenant_id, instrument_key, timeframe_unit, timeframe_interval, signal_date);

CREATE INDEX IF NOT EXISTS idx_trading_signal_lookup
    ON trading_signal (tenant_id, signal_date DESC, instrument_key, timeframe_unit, timeframe_interval);

CREATE TABLE IF NOT EXISTS trading_day_param (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    trade_date DATE NOT NULL,
    instrument_key VARCHAR(128) NOT NULL,
    orb_high NUMERIC(18, 6),
    orb_low NUMERIC(18, 6),
    orb_breakout VARCHAR(3) NOT NULL,
    orb_breakdown VARCHAR(3) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_trading_day_param_breakout CHECK (orb_breakout IN ('Yes', 'No')),
    CONSTRAINT ck_trading_day_param_breakdown CHECK (orb_breakdown IN ('Yes', 'No')),
    CONSTRAINT ck_trading_day_param_range CHECK (orb_high IS NULL OR orb_low IS NULL OR orb_low <= orb_high)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_trading_day_param_tenant_instrument_day
    ON trading_day_param (tenant_id, instrument_key, trade_date);

CREATE INDEX IF NOT EXISTS idx_trading_day_param_lookup
    ON trading_day_param (tenant_id, trade_date DESC, instrument_key);
